### ISSUE TITLE
pilot error on macos 12.6.3?

### ISSUE THREAD

**Issue by moeller0** [Zoxc/crusader#11]
trying the current crusader (just pulled and compiled) on macosx 12.6.3 (intel) against the same version server on ubuntu22 (intel) results in the following issue on the client side:
```
bash-3.2$ RUST_BACKTRACE=full ./src/target/release/crusader test 192.168.42.201
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }', crusader-lib/src/test.rs:1304:10
stack backtrace:
   0:        0x104364994 - __mh_execute_header
   1:        0x10438008b - __mh_execute_header
   2:        0x10435f208 - __mh_execute_header
   3:        0x104365ebd - __mh_execute_header
   4:        0x104365c14 - __mh_execute_header
   5:        0x1043663f8 - __mh_execute_header
   6:        0x104366333 - __mh_execute_header
   7:        0x104364e17 - __mh_execute_header
   8:        0x10436600a - __mh_execute_header
   9:        0x104394663 - __mh_execute_header
  10:        0x104394755 - __mh_execute_header
  11:        0x1042700fe - __mh_execute_header
  12:        0x1041eaa54 - __mh_execute_header
  13:        0x1041ef446 - __mh_execute_header
Abort trap: 6
```

the GUI reports error 61 as well, local testing on the client side against a locally started server (from within the GUI) seems to work.

I am pretty sure this is a simple "pilot's error" on my side, but I am at a loss what I am doing wrong here. Any help would be appreciated.

**Comment by Zoxc** [comment]
That looks like there's a firewall in place.

**Comment by moeller0** [comment]
Mmmh, thanks. I had disabled the firewall just fine, but I had requested `crusader serve --port 30481` which worked in the past, but did result in the client not finding the server anymore. Removing the `--port` request fixed the issue... as I suspected, pilot error. BTW is there a way to request/use a specific port from the client side?

**Comment by Zoxc** [comment]
You can use `--port` on the CLI from the client, but there isn't currently a GUI option for it.

**Comment by moeller0** [comment]
Thanks! I wonder now whether that ever worked or whether I just misremember this ever actually working.
