### ISSUE TITLE
Tweaks to logging

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#13]
Using crusader 0.0.10 on macOS, I see the following log messages when I run the server:

```
Server running...
Serving 192.168.253.110:60233, version 3
Serving complete for 192.168.253.110:60233
Serving 192.168.253.110:60337, version 3
Serving complete for 192.168.253.110:60337
```

A couple requests:

1. Add a date/time on each line so that people can disambiguate any tests they performed
2. In the `Server running...` message, it would be good to display the version number (e.g. `Server 0.0.10 running...`)
3. It might be useful to include the same info in the client CLI version
4. And also in the logs output by the `crusader-gui` 

Many thanks!

**Comment by mcuee** [comment]
I agree that the above are very good improvement.

**Comment by richb-hanover** [comment]
Thanks for the update!
