### ISSUE TITLE
What is crusader's "version"?

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#18]
I was trying to replicate the IPv6 crash in #9, and wasn't sure about which commit I was using for my tests. So I set about to re-run my test, and wasn't sure which version I had. 

I started looking around the repo (latest is commit a89abd2) and found these files that might have the correct "version" for Crusader:

- README - currently shows 0.0.9
- android/Cargo.toml - currently shows 0.1.0
- src/crusader/Cargo.toml - currently shows 0.0.9
- src/crusader-gui/Cargo.toml - currently shows 0.1.0
- src/crusader-gui-lib/Cargo.toml - currently shows 0.1.0
- src/crusader-lib/Cargo.toml - currently shows 0.0.10

Which should be regarded as "the correct version" for crusader? A unified version number policy would also address part of #13. 

Many thanks.

**Comment by mcuee** [comment]
Looks like `Cargo.lock` and `Cargo.toml` have the version info.
https://github.com/Zoxc/crusader/commit/a89abd26a8ea4f7272f813b1e41d223316d9c97e

**Comment by richb-hanover** [comment]
@Zoxc Thanks for the update!
