### ISSUE TITLE
How to get rid of the warning message about Load termination timed out.?

### ISSUE THREAD

**Issue by mcuee** [Zoxc/crusader#19]
Sometimes I will get the following warning, when testing wireless.
```
Warning: Load termination timed out. There may be residual untracked traffic in the background.
```

Just wondering if this is a real issue or not. If it is a real issue, how do I debug and get rid of the warning? Thanks.
Crusader version: v0.0.10-testing
Local wireless test: Asus RT-AX86U (no QoS settings enabled)
Server -- Proxmox PVE 8.0 LxC container (Ubuntu 22.04), connected to RT-AX86U 2.5G LAN port
Client -- Acer Windows 11 machine (2021 model) , Intel AX201 WiFi 6 adapter.

```
PS C:\work\speedtest\crusader-x86_64-pc-windows-msvc> .\crusader.exe test 192.168.50.12
Connected to server 192.168.50.12:35481
Latency to server 1.93 ms
Testing download...
Testing upload...
Testing both download and upload...
Warning: Load termination timed out. There may be residual untracked traffic in the background.
Writing data...
Saved raw data as data 2024.03.25 08-01-18.crr
Saved plot as plot 2024.03.25 08-01-18.png

PS C:\work\speedtest\crusader-x86_64-pc-windows-msvc> .\crusader.exe test 192.168.50.12
Connected to server 192.168.50.12:35481
Latency to server 1.60 ms
Testing download...
Testing upload...
Testing both download and upload...
Warning: Load termination timed out. There may be residual untracked traffic in the background.
Writing data...
Saved raw data as data 2024.03.25 08-02-09.crr
Saved plot as plot 2024.03.25 08-02-09.png
```

![2F8euCz](https://github.com/Zoxc/crusader/assets/1294740/84e9703c-1d17-41b0-b706-a0b43993a654)
![dOuTjqs](https://github.com/Zoxc/crusader/assets/1294740/52ca7a3d-6214-47a2-86ee-e31a07a97908)

**Comment by mcuee** [comment]
No issues with wired tests.

Local wired test: Asus RT-AX86U (no QoS settings)
Server -- Proxmox PVE 8.0 LxC container (Ubuntu 22.04), connected to RT-AX86U 2.5G LAN port
Client -- Acer Windows 11 machine (2021 model) , Ugreen USB 3.0 to gigabit Ethernet adapter

![XbM7B9q](https://github.com/Zoxc/crusader/assets/1294740/572c91a9-cfda-4892-857d-9d0e122cf6d8)
![wp11x3v](https://github.com/Zoxc/crusader/assets/1294740/e44c41d7-bdad-4153-84af-ee57bf9db6bf)

**Comment by Zoxc** [comment]
That may happen due to the TCP termination being lost or TCP incompatibilities between OSes.

It's likely benign if you see bandwidth and latency drop to idle numbers after the tests in the graph. Which we do see in the upload test with the extended wait for the TCP termination packet.

**Comment by mcuee** [comment]
I see. Thanks. I will close this issue then.
