### ISSUE TITLE
Feature Request: Place results of tests in a folder

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#23]
Currently, crusader 0.0.11 places all the test results inside the folder _src/target/release_. After a while, this leads to the situation where there are tons of assorted files mingled in that directory. The result files aren't easy to find, or more importantly to manage (or simply delete). For example...

```
                                                   ...
-rw-rw-r--   1 deploy deploy  273125 Jul 30 12:00 'data 2024.07.30 12-00-29.crr'
-rw-rw-r--   1 deploy deploy  301132 Jul 30 12:22 'data 2024.07.30 12-22-14.crr'
-rw-rw-r--   1 deploy deploy  278201 Jul 30 12:22 'data 2024.07.30 12-22-52.crr'
-rw-rw-r--   1 deploy deploy  275953 Jul 30 12:23 'data 2024.07.30 12-23-23.crr'
-rw-rw-r--   1 deploy deploy  271993 Jul 30 12:28 'data 2024.07.30 12-28-56.crr'
                                                   ...
drwxrwxr-x   2 deploy deploy   49152 Jul 29 23:06  deps/
drwxrwxr-x   2 deploy deploy    4096 Jul 29 23:00  examples/
drwxrwxr-x   2 deploy deploy    4096 Jul 29 23:00  incremental/
-rw-rw-r--   1 deploy deploy     753 Jul 29 23:06  libcrusader_gui_lib.d
-rw-rw-r--   2 deploy deploy 1047050 Jul 29 23:05  libcrusader_gui_lib.rlib
-rw-rw-r--   1 deploy deploy     681 Jul 29 23:06  libcrusader_lib.d
-rw-rw-r--   2 deploy deploy 7255414 Jul 29 23:05  libcrusader_lib.rlib
                                                   ...
-rw-rw-r--   1 deploy deploy  164490 Jul 30 12:00 'plot 2024.07.30 12-00-29.png'
-rw-rw-r--   1 deploy deploy  113378 Jul 30 12:22 'plot 2024.07.30 12-22-14.png'
-rw-rw-r--   1 deploy deploy  153845 Jul 30 12:22 'plot 2024.07.30 12-22-52.png'
-rw-rw-r--   1 deploy deploy  132865 Jul 30 12:23 'plot 2024.07.30 12-23-23.png'
-rw-rw-r--   1 deploy deploy  110520 Jul 30 12:28 'plot 2024.07.30 12-28-56.png'
                                                   ...
```
**Proposal:** Save all the `plot` and `data` result files in their own directory

- The directory could be at the top level of the repo.
- The directory could be named something like, "TestResults", with or without a space (" ")
- The directory could be mentioned in the _.gitignore_ file to exclude the files from the repo

**Comment by Zoxc** [comment]
It just saves the results to the current directory. You're free to change that or move the executables elsewhere if convenient.

**Comment by richb-hanover** [comment]
My goal is always to focus on newcomers/inexperienced people who use a tool. Mixing the result files in with important source/binary files makes it (too) easy for someone to get ham-handed and remove a binary when they just meant to "clean things up"

As a first step, perhaps Crusader could save the result files in a "TestResults" directory in the current directory. It could create that directory if it doesn't exist, then save all the files there in the future. Thanks for listening

**Comment by mcuee** [comment]
This seems to be a nice feature to have.

**Comment by Zoxc** [comment]
I've changed the default behavior to use a `crusader-results` folder now.

**Comment by richb-hanover** [comment]
Thanks!
