### ISSUE TITLE
Document command-line options?

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#27]
Is there any documentation about command line options? `./crusader --help` doesn't give much information

Also, does Crusader rely on ICMP pings? Or is all network traffic on port 35481? Thanks

**Comment by Zoxc** [comment]
I added some descriptions to the options.

> Also, does Crusader rely on ICMP pings?

No, the pings are UDP.

**Comment by richb-hanover** [comment]
Ahah. I now remember that the macOS firewall was turned on and that's why the Crusader server wouldn't work (until I turned it off). Thanks.
