### ISSUE TITLE
One Dockerfile to rule them all...

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#28]
Sorry for the epic title :-)

@brettowe proposed a Dockerfile in #15 that runs the Crusader server. This is great: it removes the (significant) hassle of installing and using a rust development environment, etc. (It's a boatload easier to tell newcomers how to install Docker than Rust...)

But this Crusader container only solves part of the problem: there's no way to run either the CLI client or (more interestingly) the GUI client.

Here's a wacky thought: What would be involved in making the Docker container run all three pieces: Server, CLI Client, and GUI Client? Here are my thoughts:

- The Docker container already runs the server

- The Docker container could run a web server (in parallel with the Crusader server) that responds to commands from a web GUI as needed.

- It would be a minimal GUI to retrieve an address from the web page and invoke `./crusader test <address>` 

- The web server could return the results using the existing `.png`

- To use the interactive charts, it would be a modest project to process the `.crr` file which I assume contains the data to produce the graphs.

Does this idea even make sense? Thanks for listening.

**Comment by Zoxc** [comment]
I'm not convinced of the Docker aspect, but it might make more sense as a remote client.

**Comment by richb-hanover** [comment]
Yes - Docker takes a little getting used to - but I'm completely sold on it. I dabble in lots of different projects. I used to wind up with many, sometimes incompatible, versions of development tools: wrasslin' with pyenv, nvm, various versions of the rust tool chain, etc. I have vivid (bad) memories of trying to get a python or node project working on my laptop with exactly the right combination of library versions that don't conflict with another project.

With Docker, you create a container that bundles a known-good set of tools. When new people use the container, they get the very same versions of all the tools. And it's a piece of cake for new developers to join the project. Things just work.

And it's easy to install Docker on virtually any computer (and it's well within the capacity of anyone who'd be interested in Crusader). \<end of sales pitch>

To kick things off, I'd be willing to spend some time on the Dockerfile to build Crusader and bundle in the web server. Might this be interesting? Thanks.

**Comment by Zoxc** [comment]
I did add a simple `crusader remote` command for now which runs a web server.

**Comment by richb-hanover** [comment]
Wow! That was speedy. I like the web interface!

I still think a Dockerfile will be valuable, but `crusader remote` makes it much simpler. Thanks.

**Comment by richb-hanover** [comment]
Oh, wait... I just realized that you have pre-built binaries for all kinds of platforms: Windows, Mac, Linux, Android...

I am going to close this - most people won't need a Dockerfile to run Crusader. I'll raise a PR to update the documentation
