### ISSUE TITLE
Request for minor tweaks for Crusader

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#31]
Now that a lot of the "sharp edges" of Crusader have been ground off, I have a few requests for (what I hope to be) simple changes to the program. 

* The font used in the GUI is too light. It's hard for my "tired old eyes" to read it. A little heavier font, used everywhere, would make a big difference. _(Done, I think)_

* Be bold - I'd recommend moving the version number to `0.1.0` or even `1.0.0`. Really - it's good enough. _(Done)_

* Immediately after making a release, bump the `master` branch version number in _Cargo.toml_. I recommend adding a `-testing` string so the log messages for subsequent builds show that it's not a released version.

* While debugging it's useful to display the git commit hash along with the version number. I don't think I'd want it all the time - maybe display it when the version contains "testing"? (I use `git rev-parse --short master` to get it for bug reports) 

* Here's another common user error that Crusader could catch and produce a nice error message. When a Crusader server is already running, I currently get the following message. Perhaps it could say, "Couldn't start the Crusader server. Is another copy running?"

```
deploy@rpi4:~/src/crusader/src/target/release$ ./crusader serve
thread 'main' panicked at crusader-lib/src/serve.rs:677:10:
called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

- The filename for the saved `plot` and `data` files should use "YYYY-MM-DD" instead of using "." as the separator. I am agnostic about using "-" or "." for the saved times. _(Done)_

Thanks as always for this good tool!

**Comment by richb-hanover** [comment]
A couple more:

* The client logs a message: "Latency to server x.xx ms". Perhaps it could be "Unloaded latency to server..." to leave open the possibility that the latency might increase when there's load
* I sometimes see the message after a test, "Warning: Load termination timed out. There may be residual untracked traffic in the background." I'm not sure what that means, or what I should do about it. 
  * Does it matter?
  * Could the message give more info about what to do?

Thanks again

**Comment by richb-hanover** [comment]
PS I just tried the newest using system fonts. They look GREAT on a Mac. Thanks.

**Comment by richb-hanover** [comment]
@Zoxc I note that the latest "update egui" commit (79c925b) reverts to the previous light (non-system) font.

**Comment by Zoxc** [comment]
@richb-hanover You can check if I got the font name correct on the latest master.

**Comment by Zoxc** [comment]
> * I sometimes see the message after a test, "Warning: Load termination timed out. There may be residual untracked traffic in the background." I'm not sure what that means, or what I should do about it.

See https://github.com/Zoxc/crusader/issues/19#issuecomment-2020117391

Maybe you could mention it in your readme PR?

**Comment by richb-hanover** [comment]
> @richb-hanover You can check if I got the font name correct on the latest master.

No. I also tried other font names, and had mixed results. Substituting "Courier" in _crusader-gui/src/main.rs_ worked (changed the font), but didn't look good; I think "Helvetica" worked, but was a light font again.

I asked ChatGPT: 
> how do I specify the system font on macos in a rust program

and it responded with a bunch of malarkey that I don't understand (I don't speak Rust yet...) I don't know if the following is helpful. Thanks

---
To use the system font on macOS in a Rust program, you can use the `core-text` crate, which provides bindings to Core Text, the text layout and font-handling library on macOS.

Here's an example of how to get the system font using `core-text`:

```rust
use core_text::font_descriptor::CTFontDescriptor;
use core_text::font::CTFont;

fn main() {
    // Create a font descriptor for the system font
    let system_font_descriptor = CTFontDescriptor::new_with_name_and_size("San Francisco", 12.0);

    // Create a CTFont from the descriptor
    let system_font = CTFont::new_from_descriptor(&system_font_descriptor, 0.0).unwrap();

    // Get the name of the system font
    let system_font_name = system_font.family_name();
    println!("System font: {}", system_font_name);
}
```

This example creates a font descriptor for the system font "San Francisco" and then creates a `CTFont` object from that descriptor. You can adjust the size parameter as needed.

Make sure to include the `core-text` crate in your `Cargo.toml`:

```toml
[dependencies]
core-text = "19.0"
```

Note that "San Francisco" is the system font, but it isn't directly accessible by name like other fonts. You should use Core Text APIs to access system-specific fonts and ensure compatibility.

**Comment by richb-hanover** [comment]
> Maybe you could mention it in your readme PR?

Done.

**Comment by Zoxc** [comment]
I think I found out how to load the system font on macOS, but ab_glyph can't render it.

**Comment by richb-hanover** [comment]
> I think I found out how to load the system font on macOS, but ab_glyph can't render it.

Sigh. I would be nice to have, though. Maybe use a bold version of the font?

Also, I added another item (start the client test when someone types an IP address then presses Return) to the list at the top of this issue.

**Comment by richb-hanover** [comment]
Wait! Using 47ee225, `./crusader-gui` uses a much better (heavier) font on macOS 12.7.5. Thanks!

**Comment by richb-hanover** [comment]
I am closing this since these items are mostly complete. 

I will send a separate note asking to change how version numbers work...
