### ISSUE TITLE
Chart origin isn't locked to 0,0 (test version)

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#32]
Using `crusader-gui` from the recent (system font) commit - cafc14a on macOS, I was surprised to see that I could scroll the Results chart to negative territory, both in the time and latency directions.

This screen shot shows that the time can be scrolled to -10 (seconds before the start of the test) and to display "negative" latency values

<img width="912" alt="image" src="https://github.com/user-attachments/assets/8eaa081c-66af-4549-a390-93bd3c77b72f">

**Comment by Zoxc** [comment]
Yeah the plot component I use doesn't allow bounds. I kind of like the freedom to drag and scroll though.

**Comment by richb-hanover** [comment]
OK. I'm not fond of that behavior, but that's how 0.0.12 works (I didn't check earlier versions) so I guess I should worry about other things. Thanks - closing
