### ISSUE TITLE
Request for change to version number procedure

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#37]
Thanks for bumping to version `0.1.0` - you deserve it for all this good work :-)

BUT... I am going to state (one final time) why I am being so insistent about the version number.

1. The log files for the builds right now all say `0.1.0`. But they're not. They are _almost_ `0.1.0`
2. Someday soon, you are going to tag a build that's actually `0.1.0`. The version number in the logs will be correct. 
3. And then, moments after congratulating yourself on the good work, you're going to make another commit, and that build _won't be_ `0.1.0` - it'll be something else. 

(As I've said before), my suggestion is to add `-testing` (or `alpha` or `beta` or `ReleaseCandidate1` or some other string) to the `version` in the _.toml_ files. As soon as you tag a release, you should bump the version to N+1, and add `-testing` so that we can tell the difference.

Two other considerations:
- There are a lot of places the version shows up - five, I think. It's a pain in the patootie to update them consistently. Are there tools (github actions?) to set it once and update multiple files from a 'master'? Here are the `names` I find:
  - `crusader`
  - `crusader-lib`
  - `crusader-gui`
  - `crusader-gui-lib`
  - `crusader-android`

- During intense debugging periods, it's a pain to keep digging out the git commit hash to report the version I was actually using. It would be fun to have a log file show `... version 1.2.3-testing (abcdef)` so that I don't screw up and mistype the commit hash. (As I suggested before), it would probably only be necessary when the version contained `-testing`.

Thanks for listening.

**Comment by richb-hanover** [comment]
Thanks for the `-dev` and git hash.

**Comment by richb-hanover** [comment]
I'm assuming that you'll release 0.1.0 with a `0.1.0` version string, then create a `0.1.1-dev` (or similar) for follow-on versions. I'm closing this.

**Comment by Zoxc** [comment]
Yes. `0.1.0` is the default Cargo crate version and these will just stay at that version.

**Comment by richb-hanover** [comment]
Thanks! Closing this...
