### ISSUE TITLE
Cosmetic GUI issue

### ISSUE THREAD

**Issue by moeller0** [Zoxc/crusader#39]
On the Client (and Latency) tabs of the GUI it reads:

> Latency sample rate: XXX milliseconds
> Throughput sample rate: XXX milliseconds

technically these are sampling periods not rates/frequencies.

**Comment by richb-hanover** [comment]
I second Sebastian's comment: The labels could be "Latency sample interval:" and "Throughput sample interval:"

<img width="794" alt="image" src="https://github.com/user-attachments/assets/7ed40991-bf44-4608-9ba3-90d5d1a1a388">

**Comment by richb-hanover** [comment]
Another comment on labeling the GUI for your consideration:

* "Both" (the label for the combined throughput numbers) could simply be "Combined"

* "Total" (the label for the combined latency numbers) could also be "Combined"

Thanks

**Comment by Zoxc** [comment]
> * "Both" (the label for the combined throughput numbers) could simply be "Combined"

Would `Summed` be more precise?

> * "Total" (the label for the combined latency numbers) could also be "Combined"

Maybe `Round-trip`? as that's just the common RTT.

**Comment by moeller0** [comment]
I know, not my bike-shed, but I like the following colors best ;)

"bi-directional" or "aggregate", but combined or summed are decent colors too ;)

Regarding latency RTT/Round trip makes sense, but then it becomes tempting to call the other "upload one-way-delay" and "download one-way-delay" respectively, but that is rather long

**Comment by richb-hanover** [comment]
I like any of these. Also, RTT and OWD are short, and well-accepted abbreviations. 

Maybe there could be a new "Help" tab. For `0.1.0`, clicking it could go to the Crusader Home Page on github to provide explanations.

(Gosh, it's easy for me to envision more work for other people...) Thanks for listening
