### ISSUE TITLE
Can't run Crusader container from dockerhub

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#42]
Using Docker on macOS or on OpenWrt, I attempt to pull the [Crusader container from dockerhub](https://hub.docker.com/r/zoxc/crusader) and get this error message.

What other troubleshooting info could I provide? Thanks.

```
√ ~ % docker pull zoxc/crusader
Using default tag: latest

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview zoxc/crusader
Error response from daemon: manifest for zoxc/crusader:latest not found: manifest unknown: manifest unknown
```

**Comment by Zoxc** [comment]
It looks like you need to specify the tag, try `docker pull zoxc/crusader:0.0.12-next-server`.

**Comment by richb-hanover** [comment]
OK. I was able to pull the 0.0.12 version, but I see that you have rolled out `0.1.0` (Congratulations!)

What version should I pull now? Thanks.

**Comment by richb-hanover** [comment]
Oh wait... I'm learning how to navigate dockerhub... I'll snag [0.1-server](https://hub.docker.com/layers/zoxc/crusader/0.1-server/images/sha256-324022550214b080acae89f4ebc96c69d970ac8cbe12cefe197a92826a4a822e?context=explore)

**Comment by richb-hanover** [comment]
@Zoxc **Partial Success!** I was able to pull the container to my macOS computer and run it. I needed to use this command to launch the server container:

```
docker run --rm -p 35481:35481/tcp -p 35481:35481/udp zoxc/crusader:0.1-server
```
It seems the `docker run` must open both the TCP and UDP ports as shown above.

**However...** I also tried to run the Crusader server in a container on my brand new shiny GL MT-6000 router. I used `opkg install luci-app-dockerman dockerd` to install, then used `docker pull ... ` and the same `docker run...` command as above to start the container. 

Yet the `crusader-gui` doesn't seem to be able to connect to the OpenWrt instance. It's running on 192.168.9.1; my laptop is connected to that router via Wi-Fi to (laptop IP is 192.168.9.116). The log in the GUI shows:

```
[2024-08-21 19:31:04] Client version 0.1 running
Error: Failed to connect to server

Caused by:
    Network is unreachable (os error 51)
```
Any thoughts? (I've never run a container on OpenWrt before, so I probably screwed something up.) What other troubleshooting info could I provide? Thanks

**Comment by richb-hanover** [comment]
Update: here's the dockerman view of the container...

<img width="958" alt="image" src="https://github.com/user-attachments/assets/1acef176-5901-4edb-bbbc-1b3ac76c0dac">

**Comment by Zoxc** [comment]
I assume OpenWrt has a firewall in place you'd need to deal with?

**Comment by richb-hanover** [comment]
I am playing with the firewall, which could well be the problem. I just figured I would ask in case you knew off the top of your head. Thanks!

**Comment by richb-hanover** [comment]
Ahah! The container needs to be run with `host` network. (It had defaulted to `bridge`...)  More testing required, but that may be the entire answer.
