### ISSUE TITLE
Request for minor tweaks to `0.1.0`

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#50]
Crusader 0.1.0 is working well. Some fussy requests:

* If I forget to start the server on the other machine, I immediately get an error like this. It would be good to ask, "Is there a server running there?" (I think there are situations where this message already appears...)
  ```
  Error: Failed to connect to server
  
  Caused by:
      Operation timed out (os error 60)
  ```

* If I enter the address of a non-existent device in the GUI, I get the same message, except with long timeout - 75 seconds? A shorter timeout would be good. (Presumably there's some "liveness" test that differentiates between these two situations.)

* In the plots, it would be good to place the colors in the "time order" that is:
  * Download, Upload, Aggregate for throughput
  * Down, Up, Round-trip for latency

* In the plot created by `crusader remote` web GUI, the time stamp at the upper-left corner should be YYYY-MM-DD hh:mm:ss (the delimiters are currently swapped).
  <img width="400" alt="image" src="https://github.com/user-attachments/assets/f64e6244-3c10-4f66-9375-2df5d9be3732">

* (Longer feature request, perhaps) As I make continued tests, I have trouble remembering which plot goes with which test condition. How could the plots contain more identifying info: date&time (although they are in the filename), client and server address, a "title" string that replaces "Latency Under Load" at the top, etc.

Thanks as always.

**Comment by richb-hanover** [comment]
@Zoxc - I just reported the item above. Can you remove it?

**Comment by richb-hanover** [comment]
In the Latency Test tab:
- It would be good to allow Return to begin the test (as with the Client tab)
- It would be useful to allow Return (perhaps any key press) to pause the latency test. I saw something interesting that I wanted to memorialize, and lost it fumbling around to click the Stop button

**Comment by Zoxc** [comment]
> * Sometimes this is incorrect [1]

It does sounds like that would be your firewall buffering the packets. Crusader currently uses the median of up to 50 samples as the idle latency.

> * (very fussy comment) The baselines of the "Server Address" label and the IP address field of the Client tab don't quite line up.

Yeah, that's an `egui` bug.

**Comment by richb-hanover** [comment]
Closing - most have been implemented
