### ISSUE TITLE
Crusader builds for other OpenWrt architectures than aarch64?

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#56]
I think it would be cool to give instructions for running Crusader Server on lots of different OpenWrt devices. (And I would be willing to write the document.) I know the `aarch64...linux` build works great for the GL.iNet GL-MT6000 router. But there are a zillion combinations that I don't entirely understand. 

To get a handle on the problem, I made a table of all OpenWrt devices and their architectures. It's at: https://openwrt.org/playground/richb/alttoh To use it , enter "23.05" in the Supported Current Release column, and sort by the "Package Architecture" column. It shows many variations: 

* [aarch64_cortex-a53](https://openwrt.org/docs/techref/instructionset/aarch64_cortex-a53)
*  [aarch64_generic](https://openwrt.org/docs/techref/instructionset/aarch64_generic)
* [arm_arm1176jzf-s_vfp](https://openwrt.org/docs/techref/instructionset/arm_arm1176jzf-s_vfp)
* [arm_arm926ej-s](https://openwrt.org/docs/techref/instructionset/arm_arm926ej-s)
* [arm_cortex-a15_neon-vfpv4](https://openwrt.org/docs/techref/instructionset/arm_cortex-a15_neon-vfpv4)
* [arm_fa526](https://openwrt.org/docs/techref/instructionset/arm_fa526)
* [arm_xscale](https://openwrt.org/docs/techref/instructionset/arm_xscale)
* [i386_geode](https://openwrt.org/docs/techref/instructionset/i386_geode)
* [mips64_octeon](https://openwrt.org/docs/techref/instructionset/mips64_octeon)
* [mips_24kc](https://openwrt.org/docs/techref/instructionset/mips_24kc)
* ... and on and on...

My questions:

* Which of these architectures would support a pre-built version of Crusader?
* Is there any way to know ahead of time whether it might work? 
* Is there any profit to making more native builds or those other architectures?

Many thanks

**Comment by richb-hanover** [comment]
Good information. Thanks

**Comment by richb-hanover** [comment]
@Zoxc Follow-up: I think I understand how this works. Is the following correct? 

Once it is correct, we can talk about where/when to post it. (I'm not looking to talk Crusader up to a broad audience before you think it's ready...)

---
## Crusader on OpenWrt

The Crusader [pre-built binaries](https://github.com/Zoxc/crusader/releases/tag/v0.1) work well for certain OpenWrt devices/architectures: `aarch64`, `arm`, `x86`, and `i686`. 

To determine if your router can run a pre-built binary, look it up in the [Table of Hardware](https://openwrt.org/toh/views/toh_extended_all). Enter its model number and find its **Package architecture** column. Then retrieve the proper binary for the architecture from [latest pre-built binary page](https://github.com/Zoxc/crusader/releases) using the table below:

| Architecture | [Latest Pre-built Binary](https://github.com/Zoxc/crusader/releases) |
|-------------| -----------------|
| `aarch64`   | **crusader-aarch64-unknown-linux-musl.tar.gz** |
| `arm`       | **crusader-arm-unknown-linux-musleabihf.tar.gz** |
| `x86`       | **crusader-x86_64-unknown-linux-musl.tar.gz** |
| `i686`      | **crusader-aarch64-unknown-linux-musl.tar.gz** |
| other architectures   | _No pre-built binary_ |

_Note:_ The other architectures (`mips`, `powerpc`, `risc`, etc.) tend to be used in older devices that may not have the CPU power to run Crusader. You could try building your own version from source.

**Comment by richb-hanover** [comment]
I edited the text above - did I get it right? Thanks

**Comment by Zoxc** [comment]
You'd still want the `arm_cortex` to `arm` mapping.

**Comment by richb-hanover** [comment]
> You'd still want the arm_cortex to arm mapping.

Here's where I display my ignorance. The ToH linked above lists many, many "arm" architectures. When I search for my own router, I'll see one of the choices below.

How can I tell whether the pre-built `arm` binary for Crusader will work? Does the **crusader-arm-unknown-linux-musleabihf.tar.gz** build work on all these? On only the ones labeled "cortex"? Is there other flag/hint? Thanks.

- [arm_arm1176jzf-s_vfp](https://openwrt.org/docs/techref/instructionset/arm_arm1176jzf-s_vfp)
- [arm_arm926ej-s](https://openwrt.org/docs/techref/instructionset/arm_arm926ej-s)
- [arm_cortex-a15_neon-vfpv4](https://openwrt.org/docs/techref/instructionset/arm_cortex-a15_neon-vfpv4)
- [arm_cortex-a7](https://openwrt.org/docs/techref/instructionset/arm_cortex-a7)
- [arm_cortex-a7_neon-vfpv4](https://openwrt.org/docs/techref/instructionset/arm_cortex-a7_neon-vfpv4)
- [arm_cortex-a8_vfpv3](https://openwrt.org/docs/techref/instructionset/arm_cortex-a8_vfpv3)
- [arm_cortex-a9](https://openwrt.org/docs/techref/instructionset/arm_cortex-a9)
- [arm_cortex-a9_neon](https://openwrt.org/docs/techref/instructionset/arm_cortex-a9_neon)
- [arm_cortex-a9_vfpv3](https://openwrt.org/docs/techref/instructionset/arm_cortex-a9_vfpv3)
- [arm_fa526](https://openwrt.org/docs/techref/instructionset/arm_fa526)
- [arm_mpcore](https://openwrt.org/docs/techref/instructionset/arm_mpcore)
- [arm_xscale](https://openwrt.org/docs/techref/instructionset/arm_xscale)

**Comment by Zoxc** [comment]
Just the `arm_cortex` ones and `arm_mpcore` which is a special Cortex A9 variant for some reason.

**Comment by Zoxc** [comment]
More generally `crusader-arm-unknown-linux-musleabihf` works on ARMv7-A (and higher) processors and `crusader-aarch64-unknown-linux-musl` works on 64-bit ARMv8-A (and higher).

**Comment by richb-hanover** [comment]
Thanks. I updated the [note above](https://github.com/Zoxc/crusader/issues/56#issuecomment-2317461303) with the info so far.

I also see  that the ToH lists `aarch64_cortex-53`, `aarch64_cortex-72`, and `aarch64_generic`. Which of these would work with a pre-built binary? Anything else I should mention? Thanks again

**Comment by Zoxc** [comment]
> Which of these would work with a pre-built binary?

All of them should.

**Comment by richb-hanover** [comment]
Thanks. Any comments on the (new) Installing / Running... section? Thanks again

**Comment by Zoxc** [comment]
You'd probably want to run it as a service to deal with crashes or reboots.

https://openwrt.org/docs/techref/initscripts / https://openwrt.org/docs/guide-developer/procd-init-scripts

**Comment by richb-hanover** [comment]
Good point. I updated the description above to mention procd init scripts.

A different question: how much more work do you expect to do on Crusader before it's "good enough" to release to a broader audience? This relates to testing of new features; documentation of any new features; descriptions of how to use it; etc. I'm happy to help with some of this. Thanks again

**Comment by richb-hanover** [comment]
I'm moving this conversation to a new issue...
