### ISSUE TITLE
Error: failed to locate peer

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#57]
Using crusader-gui 0.1.1-dev (8d21822), I mistakenly clicked the "Latency peer" box, then forgot about it.

When I attempted to run a test, I got the following message:

```
[2024-08-28 14:28:59] Client version 0.1.1-dev (commit 8d218221a83cf73d94e3f368a2212b1e45a37f41) running
[2024-08-28 14:28:59] Connected to server 192.168.253.158:35481
Error: Failed to locate local peer
```

I was pretty confused: I was thinking "local peer" was the other device entered in the "Server address" field. When I paused to read the text carefully, I realized that it was the "Latency peer". To address this you might:

* Change the error message to say, "Failed to locate Latency peer" (not "local peer")
* If the Latency Peer field is empty (it was in my case), put up a modal dialog stating something to the effect that the "Latency peer entry cannot be empty"
* I'm not sure what to do if there's an entry in the Latency peer field, but it can't serve as a peer...

Thanks

**Comment by Zoxc** [comment]
> * If the Latency Peer field is empty (it was in my case), put up a modal dialog stating something to the effect that the "Latency peer entry cannot be empty"

It can be empty and it tries to discover the peer in this case, which failed.

**Comment by richb-hanover** [comment]
I guess I don't understand how this is useful: I think it would be better to put up an error dialog, or even display "Latency peer entry cannot be empty" in the log area, instead of starting the test then giving an error.

**Comment by Zoxc** [comment]
The same thing happens if you don't specify a server. It will look for one.

**Comment by richb-hanover** [comment]
OK. I'm closing this. If other people mention it, we can think about it then.
