### ISSUE TITLE
Recording "field tests" of Crusader on various devices...

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#58]
@Zoxc @dtaht The Discussions are starting to collect interesting results for Crusader results. I wonder if we should define rules for collecting data:

- Ethernet
- 2.4GHz and 5GHz test
- Is a distant test (25 ft?) useful?
- What info should be recorded about RSSI? Where should it be measured? (At the client, I presume)
- What info should be recorded about the channel width? Where should it be observed
- What other info would be useful?

Thanks

**Comment by Zoxc** [comment]
- You shouldn't run Crusader on the device your testing.

- For throughput tests you'd also want to test with a single stream to find CPU bottlenecks. That can be quite relevant for wired tests.

**Comment by richb-hanover** [comment]
See a full example at: https://github.com/Zoxc/crusader/discussions/63
