### ISSUE TITLE
What's on the horizon?

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#61]
>> how much more work do you expect to do on Crusader before it's "good enough" to release to a broader audience?
>
> I'm wondering if it makes sense to have a simplified GUI that focuses on just the client / server and hides other features and test parameters.

My two cents: No, it's not worth modifying/simplifying the GUI yet, unless you receive strong feedback and/or multiple requests that it's important. 

But there are a couple tantalizing features queued up in `0.1.1-dev`: server discovery and average lines come to mind. What else is in the pipeline?

**Comment by richb-hanover** [comment]
Not sure whether I should post this to Discussions or here...

In a one-out-of-one test, Crusader 0.2 seems to produce better results than 0.1. I ran a test from my dining room (macOS 12.7.5 running Crusader GUI 0.2 over 2.4GHz WiFi) to an Ethernetted RPi5 running Crusader server 0.2. Compare today's plot (below) to the 0.1 plot from the dining room at #40.

Is there any reason to believe that the test itself is different? Thanks

Crusader 0.2
![plot 2024-08-30 20 35 19](https://github.com/user-attachments/assets/26c46902-a984-4802-bb34-68606ae040e2)

Crusader 0.1

![plot 2024-08-26](https://private-user-images.githubusercontent.com/1094930/359157857-f6eacc96-6a43-4908-9567-0e5a5819dee8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNjE4MjIsIm5iZiI6MTcyNTA2MTUyMiwicGF0aCI6Ii8xMDk0OTMwLzM1OTE1Nzg1Ny1mNmVhY2M5Ni02YTQzLTQ5MDgtOTU2Ny0wZTVhNTgxOWRlZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzBUMjM0NTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzFiMDRmMjgzNjc0ZmY2ZDQ1YjcxZmIwZTk5MGJiNzFkM2NlOTQzYWIxNjU2NjFiOTNiYjc5NDNmOWZhMGIwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uuSQoOlyQPerdcV-GXo5QwJRx1m92Asr5P81qQrJ5G4)

**Comment by Zoxc** [comment]
> What else is in the pipeline?

Having some number summaries in the plots could be nice. I don't really have any concrete plans for features though.

> Is there any reason to believe that the test itself is different?

That's probably just Wi-Fi.

**Comment by richb-hanover** [comment]
> That's probably just Wi-Fi.

I'm not so sure. Check out the two tests: 0.1 vs 0.2 (#63 vs #55) which I believe are virtually identical test cases except for the difference in Crusader versions. It seems to me that the 0.2 results appear to be better. It could be that 0.2 actually drives more traffic, it could be a regression (bug), or it might be something else. 

Let me know if you need additional data. Thanks.

**Comment by richb-hanover** [comment]
Update: I looked again at the full 0.1 vs 0.2. The average throughput and latency appear to be substantially the same. 

But 0.2 seems to have "smoother" plots. (Also noticeable in the images above.) Could this be due to a change in the code? Thanks. 

But

**Comment by Zoxc** [comment]
> Any thoughts on why?

The default throughput sample interval and stream count changed.

**Comment by richb-hanover** [comment]
> The default throughput sample interval and stream count changed.

Yes - the change from 20msec (0.1) to 60 msec (0.2) would have smoothed out those peaks. I think this is a good change. 

I would support the numeric summaries (since I suggested it :-) Any other thoughts for near-term changes? (I have a couple other fussy items, which I'll post separately.) Thanks!

**Comment by dtaht** [comment]
I in general am aiming for 20ms.

**Comment by richb-hanover** [comment]
Release `0.3` has satisfied my curiosity

**Comment by Zoxc** [comment]
> I in general am aiming for 20ms.

60 ms helps reduce the spikes due to what seems like OS hangups (not sure what causes them). They go away at around 200 ms.
