### ISSUE TITLE
Narrative to place at top of Releases page

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#62]
It feels like a hassle to find the correct binary from the [Releases page](https://github.com/Zoxc/crusader/releases). (It's not really difficult, but the similarity of all the names makes my brain hurt. And every now and again, I download the wrong one,  curse, and then retrieve the one I wanted.)

I speculate that text like this at the top of the Releases page might make it easier to use. (I'm not certain of this, so I'm writing it out to see if I can convince myself that it's better...)

It would be really slick if the build/release system could substitute the version/tag number into the URLs below so that they could be clickable links.

Comments welcomed...

---
# Release 0.2

Crusader 0.2 has pre-built binaries for these operating systems. Download the binary below for your OS:

## Windows
*  **Windows on x86 (64-bit):** crusader-x86_64-pc-windows-msvc.zip 
* **Windows on i686 (32-bit):** crusader-i686-pc-windows-msvc.zip 

## macOS
* **macOS on Intel:** crusader-x86_64-apple-darwin.tar.gz 
* **macOS on Apple silicon (ARM):** crusader-aarch64-apple-darwin.tar.gz 

## Linux/Unix
* **Linux on x86_64:**  crusader-x86_64-unknown-linux-musl.tar.gz 
* **Linux on (newer) ARM/aarch64:** crusader-aarch64-unknown-linux-musl.tar.gz 
* **Linux on (older) ARM:** crusader-arm-unknown-linux-musleabihf.tar.gz 

## Android
* **Android:** crusader-android.apk 

## Source code
* **Zip archive:** crusader-source.zip
* **tar.gz archive:** crusader-source.tar.gz

**Comment by Zoxc** [comment]
The assert filenames could probably be changed too.

**Comment by richb-hanover** [comment]
If you alter the asset names, I would suggest putting the items in this order: "Crusader" (that's the project), OS, then specifics. This would mean that all the Windows binaries would be sorted together, as well as the Mac and Linux binaries. Perhaps they could be:

## Windows
*  **Windows on x86 (64-bit):** crusader-windows-x86_64-msvc.zip 
* **Windows on i686 (32-bit):** crusader-windows-i686-msvc.zip 

## macOS
* **macOS on Intel:** crusader-apple-darwin-x86_64.tar.gz 
* **macOS on Apple silicon (ARM):** crusader-apple-darwin-aarch64.tar.gz 

## Linux/Unix
* **Linux on x86_64:**  crusader-linux-unknown-x86_64-musl.tar.gz 
* **Linux on (newer) ARM/aarch64:** crusader-linux-unknown-aarch64-musl.tar.gz 
* **Linux on (older) ARM:** crusader-linux-unknown-arm-musleabihf.tar.gz 

## Android
* **Android:** crusader-android.apk 

## Source code
* **Zip archive:** crusader-source.zip
* **tar.gz archive:** crusader-source.tar.gz

**Question:** Why do the Linux builds have "unknown" in the name? Is it a stand-in for "generic"? Could that word be eliminated? Thanks

**Comment by richb-hanover** [comment]
PS - I asked Mr. ChatGPT, "is there a way to insert  a version or tag into the URLs of a github Releases page?" Would the answer below help customize the filenames to download the current version?

---
Yes, you can insert a version or tag directly into the URLs of a GitHub Releases page. The general structure of the URL is as follows:

1. **Latest Release**:  
   ```
   https://github.com/{owner}/{repo}/releases/latest
   ```
   This will redirect you to the latest release.

2. **Specific Tag or Version**:  
   ```
   https://github.com/{owner}/{repo}/releases/tag/{tag}
   ```
   Replace `{owner}` with the username or organization name, `{repo}` with the repository name, and `{tag}` with the specific version or tag name.

### Example:
If you have a repository `example-repo` under the user `example-user` and you want to access release `v1.0.0`, the URL would be:
```
https://github.com/example-user/example-repo/releases/tag/v1.0.0
```

This URL will take you directly to the release associated with that specific tag.

**Comment by richb-hanover** [comment]
This is terrific! I don't see a need for further changes. Thanks!
