### ISSUE TITLE
Request for minor tweaks for `0.2`

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#64]
The program is getting very good. A few fussy comments:

* I still would like to see the color sequence displayed like this so the label sequence matches the time sequence of the tests.
![Crusader colors](https://github.com/user-attachments/assets/fea64bb4-4bbe-4915-8a92-6cf1c76c55e1)

* I just realized that you can click a color to hide/show it. This is cool! I am not sure where to describe it...

* Put a time stamp on 'Test Complete" line in the log section of the GUI (and likely in `crusader test`)

* I don't understand how server discovery works - I never see an indication of server discovery in the GUI. That's not quite true - I see `(Locate local peer)` in the server and latency peer fields, but nothing I do seems to find them.

* In future commits, it would be good to include the version number in the Git commit messages. For example, "Release 0.2" and then "Bump dev version to 0.2.1-dev". That makes it easier to scan the history to find the place where a particular release came out...

**Comment by richb-hanover** [comment]
One more: Change "bandwidth" to "throughput" in the Github sub-heading so it reads "A network throughput and latency tester" 

<img width="481" alt="image" src="https://github.com/user-attachments/assets/aa0aa1bc-f11a-473c-9520-12c72428b121">

**Comment by richb-hanover** [comment]
* Curiously, the sequence of the colors in the `.png` file is different from the GUI window. I think they should be the same

<img width="88" alt="image" src="https://github.com/user-attachments/assets/290a00f4-064e-4ef7-9124-102164812ef4">

**Comment by Zoxc** [comment]
> * I see `(Locate local peer)` in the server and latency peer fields, but nothing I do seems to find them.

You just have to leave the fields empty and it will search for them instead. They need to be in the same subnet and on version 0.2. You can look at packets on UDP port 35483 at the client and server machines. There could be bugs here.

**Comment by Zoxc** [comment]
> * That makes it easier to scan the history to find the place where a particular release came out...

You'd use the git tags for that.

**Comment by richb-hanover** [comment]
>> That makes it easier to scan the history to find the place where a particular release came out...
>
> You'd use the git tags for that.

Yes, I see your point, but that's not really the use case I had in mind. As a newcomer checking out a new project, I frequently go to the Commits and review how recently there have been changes. It's helpful to see the last release date (commit message like, "Released version 0.2"), and maybe the spacing between releases. That's a measure of the "liveness" of a project.

**Comment by richb-hanover** [comment]
> > * I see `(Locate local peer)` in the server and latency peer fields, but nothing I do seems to find them.
> 
> You just have to leave the fields empty and it will search for them instead. They need to be in the same subnet and on version 0.2. You can look at packets on UDP port 35483 at the client and server machines. There could be bugs here.

I think there may be bugs. I'll file a new Issue...

**Comment by richb-hanover** [comment]
@Zoxc Another comment re: the Results tab: In the screen shot below, the latency plot only has "0" on the Y-axis - it's not possible to see the latency without scrolling. Perhaps it would be possible to draw grey values (like the Throughput plot above it) for the latency figures when a major line isn't visible

<img width="797" alt="image" src="https://github.com/user-attachments/assets/15b88291-3b5f-49c2-98c4-516fa2983d5e">

**Comment by richb-hanover** [comment]
One more...

* The Monitor test causes all the elements to be rearranged on the page (compare screen shots below) It would be better if the elements remained in place, similar to how the Client page works. Thanks

**Before the test**

<img width="502" alt="image" src="https://github.com/user-attachments/assets/083fefb2-5aec-4556-8480-b744031ad95e">

**During the test**

<img width="397" alt="image" src="https://github.com/user-attachments/assets/4895aeb6-d9a2-497f-ab41-4b565fd2aee3">

**Comment by richb-hanover** [comment]
I just noticed that the saved `.png` and `.crr` files from a particular test run have different time stamps.  (The values appear to be the time the file was saved...) 

I think it would be more helpful to have them with identical time stamps, so they could be uniquely tied together. Perhaps the file name could reflect the time the test was started...

PS I just tried "Load raw data" - this is so cool! Thanks.

**Comment by richb-hanover** [comment]
And I wanted to comment on a nice tweak you added... I like how the "Saved image as:" and "Saved raw data as:" messages are drawn on their own lines in the newest GUI client. Thanks!

<img width="402" alt="image" src="https://github.com/user-attachments/assets/d291eef5-2895-4e90-9404-492908cc4eda">

**Comment by richb-hanover** [comment]
@Zoxc Thanks for today's updates:

* re: preserving the position of the Monitor parameters. I was also hoping that the Start/Stop button position would be preserved. (That way, I won't have to move my mouse after starting the test...)
* I like the tool tips - They work as expected, and do a good job of adding info
* Do you plan to change the order of the colors on the plots?

**Comment by richb-hanover** [comment]
Addressed in `0.3`. Thanks
