### ISSUE TITLE
"Export" for `.crr` files?

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#72]
I don't currently have a need for this, but I wonder if you have a decompiler or other tool for converting data from the `.crr` files into a human-readable format. 

As I noted earlier, those files are extremely cool - they appear to contain all the data about any particular test run. I could envision a researcher who wishes to look at the raw data (sort of a level above a tcpdump) to look at the fine-grained data about a particular test. Thanks.

**Comment by mcuee** [comment]
Maybe octave script similar to the one from cake-autorate. 
https://github.com/lynxthecat/cake-autorate/blob/master/ANALYSIS.md

But I admit I know nothing about octave. 

Or maybe Python.

**Comment by richb-hanover** [comment]
On further thought: Using `hexdump -C` on a `.crr` file shows a lot of juicy strings in amongst all the binary data.

Perhaps all I want is to export a file containing that internal data structure to some format: CSV, JSON, etc. along with a narrative of how to interpret the various bits of data. 

And I re-emphasize that I don't really have a need for this data now, but another researcher might... Thanks

**Comment by Zoxc** [comment]
I added a command which converts the data files to JSON.

**Comment by richb-hanover** [comment]
Wow! That was quick. 

To use it, `./crusader export path-to-input-.crr-file` Results are saved as _whatever-the-crr-file.json_, apparently in the same directory as the original `.crr` file.

This is good enough for now - no need to add to the GUI. If someone asks for how to use the data, we can prepare a narrative to explain the details of the JSON. Thanks!
