### ISSUE TITLE
"Load from results" - too many buttons

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#74]
The "Save to results" and "Load from results" buttons in 9d2ab82b serve a useful purpose. 

* They make it easy to save data in a coordinated place/directory
* Both `png` and `crr` files have identical time stamps
* The "Save to results" allows a test title to be added to the files
* "Load from results" makes it easy to review earlier tests.
* The "link" to _crusader-results_ that opens to the Finder/File Explorer window is great.

But the GUI now has too many "weak" buttons that don't carry their weight. My recommendations:

* Remove "Save plot", "Save data", "Load data"
* Relabel the button as "Save results". It would (still) save both the `.png` and `.crr`
* Relabel the button as "Load results" 
* In the "Load results" popup, add an "Other..." link (at the bottom of the list?) that opened a file picker that let the user select the desired `.crr` file (in the event that they had one saved elsewhere...)

Justification: 
* Crusader is still in its early days. Fixing its result-storage model now may inconvenience a handful of testers, but we'll adapt. 
* If there are a dozen or two of tests in the _crusader-results_ directory, it won't ever be a problem.
* If someone generates hundreds of results that become unwieldy, they can move them to another location. The "Other..." option lets them navigate to that directory to pluck up the ones they want
* I suspect (am I correct?) that "Load results" only pulls in the `.crr` file - Crusader can recreate the `.png` from the `.crr` at any time.

<img width="676" alt="image" src="https://github.com/user-attachments/assets/bc0d988d-d70d-4088-a474-86e0cae9a550">

**Comment by Zoxc** [comment]
> But the GUI now has too many "weak" buttons that don't carry their weight.

"Save data", "Load data" would be the basic standard functionality with "Save to results" and "Load from results" being extra convenience functions. The latter seem like they would be the first to go if pruning functionality.

Merging "Save to results" and "Load from results" might be a way to reduce the button count. Not sure what to call it then.

> * I suspect (am I correct?) that "Load results" only pulls in the `.crr` file - Crusader can recreate the `.png` from the `.crr` at any time.

That's correct.

**Comment by richb-hanover** [comment]
As with #75, I can live with the current set of buttons, even though I think we can do better. In the interest of progress, I will close this.

If others comment on this, we can re-open. Thanks
