### ISSUE TITLE
Consider removing "More parameters" button

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#75]
I was about to send a note this weekend saying how I thought that Crusader was proceeding beautifully and that I appreciate your willingness to incorporate so many of my suggestions.

But the updates overnight make me say, "Oh dear. The GUI has changed a lot..." Here are my thoughts:

* I know you have talked about creating a simplified interface. But it feels to me that adding the "More parameters" button makes things more complicated. As an experienced user with Crusader, I "know too much" - I am very comfortable with the current GUI. But even as a newcomer, I never had any questions. I simply left the default values, hit "Start test" and was happy.
* The new "Reset" and "More parameters" buttons raise questions that increase the cognitive load for newcomers: 
  * What are these buttons? Do I need to understand any of them?
  * I was surprised when I clicked the More parameters button. The fields on the screen jumped around. How can I understand what the differences are? Are these all new fields? Or only some new?
  * And what does "Reset" do? 

I would strongly advocate for switching back to the original layout (removing "More parameters" and "Reset") Thank you for considering this argument. 

A couple additional notes...

* I think we are really close to a 0.3 release: the measurement improvements "under the covers"; the more robust handling of error conditions; the popup windows showing numerical summaries; the overall layout of the screens all provide a significant improvement over the 0.2 release. 
 
* I don't know if he has spoken to you, but Dave Täht is giving a talk at the Linux Plumbers conference this Wednesday. If I understood him correctly, he was planning to speak fondly about Crusader there. 

* Crusader is solving problems right now. I just responded to a query on Reddit re: Wifi latency where I gave instructions for using Crusader at: https://www.reddit.com/r/Comcast_Xfinity/comments/1fg2t7f/comment/ln2o2im/

**Comment by Zoxc** [comment]
> * And what does "Reset" do?

It resets the parameters to default. I found myself doing that manually quite a bit.

Adding the "Reset" button and the "Measure" selector ate a bit more vertical space, so an additional motivation of "More parameters" was gaining more space on Android.

I changed "More parameters" to an "Advanced Mode" toggle button with the old settings layout. You can see if that feels better.

**Comment by richb-hanover** [comment]
Ahah! I am learning more about how others (like you!) use Crusader... It's useful to know you use Reset a lot. I was thinking of mentioning the vertical screen space as well.

Here's a different idea for simplifying the interface: Let's move all the parameters to a new "Test settings" tab, perhaps that sits to the right of the Result tab.

* The main "Client" GUI would then show the following:
  * The tabs - Client / Server / Remote / Monitor / Result / Test settings
  * "Server Address:" label, text field,  and "Start test" button
  * Latency peer checkbox, "Latency peer:" label and text field (perhaps both within the horizontal lines)
  * Log area for the results of the test

* The "Test settings" tab then has room for all the settings (and any that we may add in the future). I don't know how I would lay out the following:
  * The nine settings (down/up/bidirectional, streams, load duration, etc.) 
  * The "Reset" button
  * The "Latency under load" and "Latency-only" buttons. 
  * (Is the Latency-only test identical to unchecking the Down/Up/Bidirectional boxes?)

Thanks again for listening

**Comment by richb-hanover** [comment]
OK. I have expressed my opinion, but concede that you need the program to match your desires. In the interest of moving forward, let me respond to the changes in commit 0.2.1-dev 648f15b.

I can live with the current state of the Client tab:
* "Non-advanced" mode hides the Latency peer setting. This is good - I would have moved it to the "Test settings" tab that I originally proposed.
* Could the "Latency" button be changed to read "Latency-only"?

In addition, to conserve vertical space:
* I wonder if the "Advanced Mode" button could be placed next to the "Start test" button
* ... and then the "Reset Settings" button could appear only when the Advance Mode settings are showing

I agree we should leave the Client tab GUI alone for a while until there is more feedback from other people. Thank you as always for the great work you have been doing.

**Comment by Zoxc** [comment]
> * Is the Latency-only test identical to unchecking the Down/Up/Bidirectional boxes?

Yes.
