### ISSUE TITLE
Confused by Latency numeric summary

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#76]
I was surprised to see the latency values shown in the numeric summary window. Using 648f15b, these are the differences from what I expected:

- The latency chart shows virtually all the Up and Down samples at or below 35msec except or a few spikes. Round-trip latency is about 70msec 
- Yet the latency summary window shows numbers that are very different from the chart. For example, why is the round-trip upload latency shown as 99ms, and the down and up values shown as 44 and 55ms respectively, when the chart definitely shows lower values.
- The Bidirectional latency is even more divergent - 249ms round-trip doesn't match the chart.

_(I will note that the throughput and packet loss values are quite believable.)_

I attach the corresponding `.crr` file. What other troubleshooting info could I collect? Thanks

<img width="799" alt="image" src="https://github.com/user-attachments/assets/74ceee1e-4729-45c9-86e5-30cb28cc5099">

[Odd-Latency 2024-09-14 22.56.53.crr.zip](https://github.com/user-attachments/files/17004449/Odd-Latency.2024-09-14.22.56.53.crr.zip)

**Comment by Zoxc** [comment]
Latency is smoothed using the average of a 400 ms window. The peak of that is the latency value displayed. This matches the edited screenshot, but the original still seems off. I assume you didn't save that one?

I wonder if latency summaries should be shown relative to idle like the Waveform test too.

**Comment by richb-hanover** [comment]
I didn't save the original `.crr` file. Dang.

I think this can be handled by documentation... There's so much new in Crusader - we'll need to write up something to describe the contents of those windows. 

I'll take a shot at the wording (below). Perhaps this turns into a separate "Understanding Crusader GUI" page on the repo.

**Comment by richb-hanover** [comment]
See #78
