### ISSUE TITLE
Next release of Crusader? 

### ISSUE THREAD

**Issue by richb-hanover** [Zoxc/crusader#77]
I seem to be running out of things to complain about :-) Is it time to start thinking of another release?

Here are my outstanding questions. Do you want to address any of them?

* Better error message when peer can speak to server #73

* Changing order of the plots colors both in GUI and in the PNG https://github.com/Zoxc/crusader/issues/64#issue-2501082035 (You have not responded to this in the past. Perhaps you are not inclined to make this change...?)

* I can live with #74 and #75 in the current state.

* I noticed an odd commit hash in the GUI I built just now. The client log shows `[2024-09-15 10:03:46] Client version 0.2.1-dev (commit 648f15b) running`. But this obviously is the latest fd4c064 because the stats are there, and the button was "Latency only". This isn't anything to hold up a new release, just a curiosity...

Thanks!

<img width="802" alt="image" src="https://github.com/user-attachments/assets/810235d1-0cf2-405b-89d7-c860df3b8d14">

**Comment by richb-hanover** [comment]
@Zoxc PS I want to emphasize that I think Crusader is getting extremely good... Thanks again

**Comment by Zoxc** [comment]
> * Better error message when peer can speak to server

That can probably be done after a 0.3 version.

> * I noticed an odd commit hash in the GUI I built just now.

The build script that fetches the Git commit runs when `crusader-lib` changes which didn't happen here.

> * Changing order of the plots colors both in GUI and in the PNG

I'd need to change the `egui_plot` crate for that.

**Comment by richb-hanover** [comment]
These are all great answers. Do you think we're looking at a  0.3 release soon? (That would delight me, and maybe also Dave Täht, who's giving a talk on Wednesday...)

As I see it, we'd need to do the following:

* No code changes (unless you know of any burning issues)
* Bump the version to 0.3 (or 1.0?)
* Build the releases, push to the Releases page
* Update screen shots in the README showing the new version number
* Publish an UNDERSTANDING.md page, with the text similar to #78 (I'd welcome your comments)
* Final editorial pass over all the documentation

I could do the last three items within 24 hours of getting the new release (so I can take screen shots) Thanks

**Comment by Zoxc** [comment]
Well you got yourself a release and some plot legend reordering.

**Comment by richb-hanover** [comment]
> Well you got yourself a release and some plot legend reordering.

Thanks! The `0.3` release is a thing of beauty! I'd like to get comments on the documentation PR. Thanks again

**Comment by richb-hanover** [comment]
PS - Crusader was mentioned a couple times at today's Linux Plumbers conference session: https://lpc.events/event/18/contributions/1967/attachments/1491/3153/State%20of%20the%20Bloat.pdf

Congratulations!
